<ul class="nav nav-list">
	<li class="nav-header">
		教学服务器入口
	</li>
	<li class="active">
		<a href="index.php"><i class="icon-white icon-home"></i>计算机学院基础教育中心</a>
	</li>
	<li>
		<a href="10.77.30.31"><i class="icon-folder-open"></i> C在线练习[入口1] </a>
	</li>
	<li>
		<a href="10.77.30.30"><i class="icon-check"></i> C在线练习[入口2] </a>
	</li>
	<li>
		<a href="10.77.30.58"><i class="icon-envelope"></i>上机实验预约入口</a>
	</li>
