<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="#">Akira</a>
      <div class="nav-collapse">
	<ul class="nav">
		<li class="active">
			<a href="index.html">首页</a>
		</li>
		
		<li class="dropdown">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			公告通知 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="help.htm">发布公告</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">公告列表</a>
				</li>
			</ul>
		</li>

		<li class="dropdown">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			课程管理 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="help.htm">模板课程</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">课程知识点</a>
				</li>
			</ul>
		</li>

		<li class="dropdown">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			试卷题库 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="/cstcx/admin/paper/subindex.php">试题管理</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">试卷结构</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">模板试卷</a>
				</li>
			</ul>
		</li>

		<li class="dropdown">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			系统用户 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="help.htm">教师用户</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">课程班级</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">用户查询</a>
				</li>
			</ul>
		</li>

		<li class="dropdown">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			系统工具 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="help.htm">资源管理</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">资源查询</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">个人信息</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">系统选项</a>
				</li>
			</ul>
		</li>
		<li class="dropdown">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">帮助 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="help.htm">操作指导</a>
				</li>
			</ul>
		</li>
	</ul>
		
		
		<form class="navbar-search pull-left" action="">
			<input type="text" class="search-query span2" placeholder="Search" />
		</form>

		<ul class="nav pull-right">
			<li>
				<a href="profile.htm">管理员</a>
			</li>
			<li>
				<a href="index.php">Logout</a>
			</li>
		</ul>
	</div>
</div>
</div>
</div>
