<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> 
			<span class="icon-bar"></span> <span class="icon-bar"></span> 
			<span class="icon-bar"></span> </a> <a class="brand" href="#">
			计算机学院基础教学课程中心
			</a>
			<div class="nav-collapse">
			<ul class="nav">
				<li class="active" id="index">
					<a href="../index/index_stu.php">首页</a>
				</li>
				<li class="dropdown"  id="notice">
					<a href="message.php" class="dropdown-toggle" 
					data-toggle="dropdown">通知 <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li>
							<a href="help.htm">中心通知</a>
						</li>
						
						<li class="divider">
						</li>
						<li>
							<a href="help.htm">课程通知</a>
						</li>
						
					</ul>
				</li>

				<li class="dropdown" id="course">
					<a href="message.php" class="dropdown-toggle" 
					data-toggle="dropdown">课程 <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li>
							<a href="help.htm">公共课程</a>
						</li>
						
						<li class="divider">
						</li>
						<li>
							<a href="help.htm">我的课程</a>
						</li>
						
					</ul>
				</li>
				<li class="dropdown" id="download">
					<a href="message.php" class="dropdown-toggle" 
					data-toggle="dropdown">下载 <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li>
							<a href="help.htm">常用软件</a>
						</li>
						
						<li class="divider">
						</li>
						<li>
							<a href="help.htm">课程资源</a>
						</li>
						<li class="divider">
						</li>
						<li>
							<a href="help.htm">历年试卷</a>
						</li>
						
					</ul>
				</li>
				<li class="dropdown" id="setting">
					<a href="message.php" class="dropdown-toggle" 
					data-toggle="dropdown">设置 <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li>
							<a href="../profile/profile.php">个人信息</a>
						</li>
						
						<li class="divider">
						</li>
						<li>
							<a href="help.htm">修改密码</a>
						</li>
						<li class="divider">
						</li>
						<li>
							<a href="help.htm">系统参数</a>
						</li>
						
					</ul>
				</li>
				<li class="dropdown" id="homework">
					<a href="message.php" class="dropdown-toggle" 
					data-toggle="dropdown">作业 <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li>
							<a href="help.htm">实验报告</a>
						</li>
						
						<li class="divider">
						</li>
						<li>
							<a href="help.htm">课程作业</a>
						</li>
						<li class="divider">
						</li>
						<li>
							<a href="help.htm">模拟测验</a>
						</li>
						<li>
							<a href="help.htm">编程练习</a>
						</li>
						
					</ul>
				</li>
				<li class="dropdown" id="help">
					<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">帮助 <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li>
							<a href="help.htm">Introduction Tour</a>
						</li>
						<li>
							<a href="help.htm">Project Organisation</a>
						</li>
						<li>
							<a href="help.htm">Task Assignment</a>
						</li>
						<li>
							<a href="help.htm">Access Permissions</a>
						</li>
						<li class="divider">
						</li>
						<li class="nav-header">
							Files
						</li>
						<li>
							<a href="help.htm">How to upload multiple files</a>
						</li>
						<li>
							<a href="help.htm">Using file version</a>
						</li>
					</ul>
				</li>
			</ul>
			<form class="navbar-search pull-left" action="">
				<input type="text" class="search-query span2" placeholder="Search" />
			</form>
			<ul class="nav pull-right">
				
				<li>
					<a href="../profile/profile.php" id="name">汪波</a>
				</li>
				<li>
					<a href="../login/logout.php">注销</a>
				</li>
			</ul>
			</div>
		</div>
	</div>
</div>
