<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="#">计算机学院基础教学中心网站</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="active">
						<a href="index.php">首页</a>
					</li>
					<li>
						<a href="#">资源</a>
					</li>
					<li>
						<a href="#">课程</a>
					</li>
					
				</ul>
				<form class="navbar-search pull-left" action="" style="float:right">
					<input type="text" class="search-query span2" placeholder="Search" />
				</form>
				<!--
				<ul class="nav pull-right">
					<li>
						<a href="profile.htm">@username</a>
					</li>
					<li>
						<a href="login.php">Logout</a>
					</li>
				</ul>
				-->
			</div>
		</div>
	</div>
</div>
