<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="#">计算机学院</a>

      <div class="nav-collapse">
	<ul class="nav">
		<li class="active" id="index">
			<a href="../index/index_tea.php">首页</a>
		</li>
		
		<li class="dropdown" id="notice">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			公告通知 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="../news/publish.php">发布公告</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">公告列表</a>
				</li>
			</ul>
		</li>

		<li class="dropdown" id="course">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			课程管理 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="../course/newcourse.php?course=自定义课程">新增课程</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="../course/CourseList.php">课程列表</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">课程知识点</a>
				</li>
			</ul>
		</li>

		<li class="dropdown" id="sublib">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			试卷题库 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="../sublib/SubLib.php">试题管理</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">试卷管理</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">模板试卷</a>
				</li>
			</ul>
		</li>

		<li class="dropdown">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			系统用户 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="help.htm">教师用户</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">课程班级</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">用户查询</a>
				</li>
			</ul>
		</li>

		<li class="dropdown" id="setting">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">
			系统工具 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="help.htm">资源管理</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">资源查询</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="../profile/profile.php">个人信息</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="help.htm">系统选项</a>
				</li>
			</ul>
		</li>
		<li class="dropdown">
			<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">帮助 <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li>
					<a href="help.htm">操作指导</a>
				</li>
			</ul>
		</li>
	</ul>
		
		
		<form class="navbar-search pull-left" action="">
			<input type="text" class="search-query span2" placeholder="Search" />
		</form>

		<ul class="nav pull-right">
			<li>
				<a href="../profile/profile.php" id="name">demo</a>
			</li>
			<li>
				<a href="../login/logout.php">注销</a>
			</li>
		</ul>
	</div>
</div>
</div>
</div>

