<div class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="#">计算机学院基础教学中心网站</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="active">
						<a href="index.php">首页</a>
					</li>
					<li>
						<a href="settings.htm">消息</a>
					</li>
					<li>
						<a href="help.htm">课程</a>
					</li>
					<li class="dropdown">
						<a href="help.htm" class="dropdown-toggle" data-toggle="dropdown">Tours <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<a href="help.htm">Introduction Tour</a>
							</li>
							<li>
								<a href="help.htm">Project Organisation</a>
							</li>
							<li>
								<a href="help.htm">Task Assignment</a>
							</li>
							<li>
								<a href="help.htm">Access Permissions</a>
							</li>
							<li class="divider">
							</li>
							<li class="nav-header">
								Files
							</li>
							<li>
								<a href="help.htm">How to upload multiple files</a>
							</li>
							<li>
								<a href="help.htm">Using file version</a>
							</li>
						</ul>
					</li>
				</ul>
				<form class="navbar-search pull-left" action="">
					<input type="text" class="search-query span2" placeholder="Search" />
				</form>
				<!--
				<ul class="nav pull-right">
					<li>
						<a href="profile.htm">@username</a>
					</li>
					<li>
						<a href="login.php">Logout</a>
					</li>
				</ul>
				-->
			</div>
		</div>
	</div>
</div>
