
<ul id="myTab" class="nav nav-tabs">
   <li class="active">
      <a href="#home" data-toggle="tab">
         首页
      </a>
   </li>
   
   <li><a href="#ios" data-toggle="tab">公告通知</a></li>
   
   <li class="dropdown">
      <a href="#" id="myTabDrop1" class="dropdown-toggle" 
         data-toggle="dropdown">课程管理 
         <b class="caret"></b>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop1">
         <li><a href="#jmeter" tabindex="-1" data-toggle="tab">模板课程</a></li>
         <li><a href="#ejb" tabindex="-1" data-toggle="tab">课程知识点</a></li>
      </ul>
   </li>

   <li class="dropdown">
      <a href="#" id="myTabDrop2" class="dropdown-toggle" 
         data-toggle="dropdown">试卷题库 
         <b class="caret"></b>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop2">
         <li><a href="subindex.php" tabindex="-1" data-toggle="tab" data-target="subindex.php">试题管理</a></li>
	 	<li class="divider"></li>
         <li><a href="subindex.php" tabindex="-1" data-toggle="tab">试卷结构</a></li>
	 	<li class="divider"></li>
          <li><a href="../../index.php" tabindex="-1" data-toggle="tab">试卷知识点</a></li>
      </ul>
   </li>

   <li class="dropdown">
      <a href="#" id="myTabDrop3" class="dropdown-toggle" 
         data-toggle="dropdown">系统用户 
         <b class="caret"></b>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop3">
         <li>
		<a href="help.htm" tabindex="-1" data-toggle="tab">教师用户</a>
	</li>
	<li class="divider"></li>
	<li>
		<a href="help.htm" tabindex="-1" data-toggle="tab">课程班级</a>
	</li>
	<li class="divider" tabindex="-1" data-toggle="tab"></li>
	<li>
		<a href="help.htm" tabindex="-1" data-toggle="tab">用户查询</a>
	</li>
      </ul>
   </li>

   <li class="dropdown">
      <a href="#" id="myTabDrop4" class="dropdown-toggle" 
         data-toggle="dropdown">系统工具 
         <b class="caret"></b>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="myTabDrop4">
         <li tabindex="-1" data-toggle="tab"><a href="subindex.php">资源管理</a></li>
 	 <li class="divider"></li>
	 <li><a href="help.htm">资源查询</a></li>
	 <li class="divider"></li>
	 <li><a href="help.htm">个人信息</a></li>
	 <li class="divider"></li>
	 <li><a href="help.htm">系统选项</a></li>
      </ul>
	
   </li>
   
   <li><a href="#ios" data-toggle="tab">帮助</a></li>

</ul>

