<ul class="nav nav-list">
	<li class="nav-header">
		常用链接
	</li>
	<li class="active">
		<a href="http://localhost/Teachers/web/index/index_tea.php"><i class="icon-white icon-home"></i> 主页</a>
	</li>
	<li>
		<a href="http://localhost/Teachers/web/course/CourseList.php"><i class="icon-folder-open"></i> 课程列表</a>
	</li>
	<li>
		<a href="tasks.htm"><i class="icon-check"></i> 公告列表</a>
	</li>
	<li>
		<a href="messages.htm"><i class="icon-envelope"></i> 用户查询</a>
	</li>


	<li class="nav-header">
		账户设置
	</li>
	<li>
		<a href="profile.htm"><i class="icon-user"></i> 个人信息</a>
	</li>
	<li>
		<a href="settings.htm"><i class="icon-cog"></i> 系统设置</a>
	</li>
	<li class="divider">
	</li>
	<li>
		<a href="help.htm"><i class="icon-info-sign"></i> 帮助</a>
	</li>
	<li class="nav-header">
		友情链接
	</li>
	<li>
		<a href="http://jwbinfosys.zju.edu.cn/"><i class="icon-picture"></i> 教务网</a>
	</li>
	<li>
		<a href="http://www.cc98.org"><i class="icon-stop"></i> CC98</a>
	</li>
</ul>
