TYPE=VIEW
query=select `a`.`esDefID` AS `esDefID`,`a`.`esInsFileUrl` AS `esInsFileUrl`,`a`.`esInsUploadDate` AS `esInsUploadDate`,`b`.`examDefID` AS `examDefID`,`c`.`subID` AS `subID`,`c`.`coID` AS `coID`,`c`.`subBH` AS `subBH`,`c`.`subTitle` AS `subTitle`,`c`.`subCont` AS `subCont`,`c`.`subLx` AS `subLx`,`c`.`subInput` AS `subInput`,`c`.`subOutput` AS `subOutput`,`c`.`subStatus` AS `subStatus`,`c`.`subDesc` AS `subDesc`,\'??\' AS `esUploadStatus` from ((`db_cjh`.`T_ExamSubInst` `a` join `db_cjh`.`T_ExamSubDef` `b`) join `db_cjh`.`T_Subject` `c`) where ((`a`.`esDefID` = `b`.`esDefID`) and (`b`.`subID` = `c`.`subID`)) union select `a`.`esDefID` AS `esDefID`,\'\' AS `esInsFileUrl`,\'\' AS `esInsUploadDate`,`a`.`examDefID` AS `examDefID`,`b`.`subID` AS `subID`,`b`.`coID` AS `coID`,`b`.`subBH` AS `subBH`,`b`.`subTitle` AS `subTitle`,`b`.`subCont` AS `subCont`,`b`.`subLx` AS `subLx`,`b`.`subInput` AS `subInput`,`b`.`subOutput` AS `subOutput`,`b`.`subStatus` AS `subStatus`,`b`.`subDesc` AS `subDesc`,\'??\' AS `esUploadStatus` from (`db_cjh`.`T_ExamSubDef` `a` join `db_cjh`.`T_Subject` `b`) where ((`a`.`subID` = `b`.`subID`) and (not(`a`.`esDefID` in (select `a`.`esDefID` from ((`db_cjh`.`T_ExamSubInst` `a` join `db_cjh`.`T_ExamSubDef` `b`) join `db_cjh`.`T_Subject` `c`) where ((`a`.`esDefID` = `b`.`esDefID`) and (`b`.`subID` = `c`.`subID`))))))
md5=805064f9a0e37c0ec41f59cc5c8b3106
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2014-08-09 09:52:58
create-version=1
source=select `a`.`esDefID` AS `esDefID`,`a`.`esInsFileUrl` AS `esInsFileUrl`,`a`.`esInsUploadDate` AS `esInsUploadDate`,\n`b`.`examDefID` AS `examDefID`,`c`.`subID` AS `subID`,`c`.`coID` AS `coID`,`c`.`subBH` AS `subBH`,`c`.`subTitle` AS `subTitle`,`c`.`subCont` AS `subCont`,\n`c`.`subLx` AS `subLx`,`c`.`subInput` AS `subInput`,`c`.`subOutput` AS `subOutput`,`c`.`subStatus` AS `subStatus`,`c`.`subDesc` AS `subDesc`,\'??\' AS `esUploadStatus` \nfrom ((`T_ExamSubInst` `a` join `T_ExamSubDef` `b`) join `T_Subject` `c`) \nwhere ((`a`.`esDefID` = `b`.`esDefID`) and (`b`.`subID` = `c`.`subID`))\n union \n select `a`.`esDefID` AS `esDefID`,\'\' AS `esInsFileUrl`,\'\' AS `esInsUploadDate`,`a`.`examDefID` AS `examDefID`,`b`.`subID` AS `subID`,\n `b`.`coID` AS `coID`,`b`.`subBH` AS `subBH`,`b`.`subTitle` AS `subTitle`,`b`.`subCont` AS `subCont`,`b`.`subLx` AS `subLx`,`b`.`subInput` AS `subInput`,\n `b`.`subOutput` AS `subOutput`,`b`.`subStatus` AS `subStatus`,`b`.`subDesc` AS `subDesc`,\'??\' AS `esUploadStatus` \n from (`T_ExamSubDef` `a` join `T_Subject` `b`) where ((`a`.`subID` = `b`.`subID`) \n and (not(`a`.`esDefID` in (select `a`.`esDefID` from ((`T_ExamSubInst` `a` join `T_ExamSubDef` `b`) \n join `T_Subject` `c`) where ((`a`.`esDefID` = `b`.`esDefID`) and (`b`.`subID` = `c`.`subID`))))))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `a`.`esDefID` AS `esDefID`,`a`.`esInsFileUrl` AS `esInsFileUrl`,`a`.`esInsUploadDate` AS `esInsUploadDate`,`b`.`examDefID` AS `examDefID`,`c`.`subID` AS `subID`,`c`.`coID` AS `coID`,`c`.`subBH` AS `subBH`,`c`.`subTitle` AS `subTitle`,`c`.`subCont` AS `subCont`,`c`.`subLx` AS `subLx`,`c`.`subInput` AS `subInput`,`c`.`subOutput` AS `subOutput`,`c`.`subStatus` AS `subStatus`,`c`.`subDesc` AS `subDesc`,\'??\' AS `esUploadStatus` from ((`db_cjh`.`T_ExamSubInst` `a` join `db_cjh`.`T_ExamSubDef` `b`) join `db_cjh`.`T_Subject` `c`) where ((`a`.`esDefID` = `b`.`esDefID`) and (`b`.`subID` = `c`.`subID`)) union select `a`.`esDefID` AS `esDefID`,\'\' AS `esInsFileUrl`,\'\' AS `esInsUploadDate`,`a`.`examDefID` AS `examDefID`,`b`.`subID` AS `subID`,`b`.`coID` AS `coID`,`b`.`subBH` AS `subBH`,`b`.`subTitle` AS `subTitle`,`b`.`subCont` AS `subCont`,`b`.`subLx` AS `subLx`,`b`.`subInput` AS `subInput`,`b`.`subOutput` AS `subOutput`,`b`.`subStatus` AS `subStatus`,`b`.`subDesc` AS `subDesc`,\'??\' AS `esUploadStatus` from (`db_cjh`.`T_ExamSubDef` `a` join `db_cjh`.`T_Subject` `b`) where ((`a`.`subID` = `b`.`subID`) and (not(`a`.`esDefID` in (select `a`.`esDefID` from ((`db_cjh`.`T_ExamSubInst` `a` join `db_cjh`.`T_ExamSubDef` `b`) join `db_cjh`.`T_Subject` `c`) where ((`a`.`esDefID` = `b`.`esDefID`) and (`b`.`subID` = `c`.`subID`))))))
